models.py
from datetime import datetime
from extensions import db


class BooksToRead(db.Model):

    __tablename__ = 'books_to_read'

    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.String(255), nullable=False)
    title = db.Column(db.String(255), unique=True, nullable=False)
    created = db.Column(db.DateTime, default=datetime.utcnow())

    def __init__(self, author, title) -> None:
        self.author = author
        self.title = title

    @classmethod
    def get_all(cls):
        return cls.query.all()

    @classmethod
    def get_book(cls, title):
        return cls.query.filter_by(title=title).first()

    @classmethod
    def add_book(cls, book):
        db.session.add(book)
        db.session.commit()

    @classmethod
    def delete_book(self, book):
        db.session.delete(book)
        db.session.commit()

    def __repr__(self) -> str:
        return f"{self.author} - {self.title}"


class FinishedBooks(db.Model):

    __tablename__ = 'finished_books'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), unique=True, nullable=False)
    author = db.Column(db.String(255), unique=True, nullable=False)
    created = db.Column(db.DateTime, default=datetime.utcnow())

    def __init__(self, author, title) -> None:
        self.author = author
        self.title = title

    @classmethod
    def get_all(cls):
        return cls.query.all()

    @classmethod
    def get_book(cls, title):
        return cls.query.filter_by(title=title).first()

    @classmethod
    def add_book(cls, book):
        db.session.add(book)
        db.session.commit()

    @classmethod
    def delete_book(self, book):
        db.session.delete(book)
        db.session.commit()

    def __repr__(self) -> str:
        return f"{self.author} - {self.title}"

core/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class BookForm(FlaskForm):

    author = StringField('Author', validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired()])
    submit = SubmitField('Add Book')

app.py
import os
from flask import Flask
from extensions import db


def import_blueprints():
    global core_blueprint

    from core.views import core_blueprint


def register_extensions(app):
    db.init_app(app)


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    import_blueprints()
    register_extensions(app)

    app.register_blueprint(core_blueprint)

    @app.before_first_request
    def create_tables():
        db.create_all()

    return app, db


config = os.environ['APP_SETTINGS']
app, database = create_app(config)

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5000, debug=True)

core/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for)
from .forms import BookForm
from models import BooksToRead, FinishedBooks

core_blueprint = Blueprint(
    'core',
    __name__,
    template_folder='templates'
)


def get_args():
    finished_books = FinishedBooks.get_all()
    finished_count = len(finished_books)
    return {
        'form': BookForm(),
        'to_read': BooksToRead.get_all(),
        'finished_books': finished_books,
        'finished_count': finished_count
    }


@core_blueprint.route('/', methods=['GET', 'POST'])
def index():
    args = get_args()
    form = args.get('form')
    if form.validate_on_submit():
        book = BooksToRead(
            author=form.author.data,
            title=form.title.data
        )
        BooksToRead.add_book(book)
        flash(f'{form.title.data} added', 'message')
        return redirect(url_for('core.index'))
    return render_template('index.html', **args)


@core_blueprint.route('/delete/<string:title>', methods=['POST'])
def delete(title):
    if request.args.get('column') == 'to_read':
        book = BooksToRead.get_book(title)
        BooksToRead.delete_book(book)
    else:
        book = FinishedBooks.get_book(title)
        FinishedBooks.delete_book(book)
    flash(f'{title} deleted!', 'message')
    return redirect(url_for('core.index'))


@core_blueprint.route('/complete/<string:title>', methods=['POST'])
def complete(title):
    book = BooksToRead.get_book(title)
    finished_book = FinishedBooks(
        author=book.author,
        title=book.title
    )
    FinishedBooks.add_book(finished_book)
    BooksToRead.delete_book(book)
    flash(f'{title} completed!', 'message')
    return redirect(url_for('core.index'))

core/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="shortcut icon" href="{{ url_for('static', filename='images/book.ico') }}" type="image/x-icon">
        <title>Book Tracker App</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}" type="text/css">
        <script src="{{ url_for('static', filename='reload.js') }}"></script>
    </head>
    <body>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}
                <div class="flash-container">
                    <p class="{{category}}">{{message}}</p>
                </div>
            {% endfor %}
        {% endwith %}
            
        <main class="page-main">
            <h1>Book Tracker App</h1>
            <h3>Start Date: 20/05/2021</h3>
            <div class="form-container">
                <form class="add-book-form" action="{{ url_for('core.index') }}" method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.author.label(class='form-label') }}
                    {{ form.author(class='form-input') }} 
                    {{ form.title.label(class='form-label') }}
                    {{ form.title(class='form-input') }} 
                    {{ form.submit(class='form-submit-btn', onclick="reloadPage()") }} 
                </form>
                <p class="finished-total">Total finished books: <span class="finished-count">{{ finished_count }}</span></p>
            </div>
            <div class="outer-books-container">
                <div class="books-to-read-container">
                    <h2>Reading List</h2>
                    {% for book in to_read %}
                        <div class="book-details-container to-read">
                            <p class="book-author">{{ book.author }}</p>
                            <p class="book-title">{{ book.title }}</p>
                            <div class="book-btns-container">
                                <form action="{{ url_for('core.complete', title=book.title) }}" method="post" onclick="reloadPage()">
                                    <input class="mark-complete-btn" type="submit" value="Mark Complete">
                                </form>
                                <form action="{{ url_for('core.delete', title=book.title, column='to_read') }}" method="post" onclick="reloadPage()">
                                    <input class="delete-btn" type="submit" value="Delete">
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="finished-books-container">
                    <h2>Finished Books</h2>
                    {% for book in finished_books %}
                        <div class="book-details-container finished">
                            <p class="book-author">{{ book.author }}</p>
                            <p class="book-title">{{ book.title }}</p>
                            <div class="book-btns-container">
                                <form action="{{ url_for('core.delete', title=book.title, column='finished') }}" method="post" onclick="reloadPage()">
                                    <input class="delete-btn" type="submit" value="Delete">
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>   
        </main>
        <script src="{{ url_for('static', filename='main.js') }}"></script>
    </body>
</html>